### ISSUE TITLE
About "Train" term

### ISSUE THREAD

**Issue by deeptechs** [malikshubham827/get-me-through#3]
I guess you used the term "Train" to represent saving known person images to db. If so, it would be more clear to use the term "Enroll" for this purpose.

"Training" shortly means, giving the data to the algorithm and expecting that the algorithm can learn the nature of the data so it can predict the unknown ones. The model you used (about %99 accuracy) already trained with millions of face images.

Great work.

**Comment by malikshubham827** [comment]
Yeah, it's just the matter of personal preference. It striked me when writing that. Yeah technically it's not for training.
